Add support for Unreal Engine 4.27
ZhengzhongSun/BPDiffer pull request #1
Opened 2024-11-02 19:50 UTC by waelarafa

Pull Request Title:
Add support for Unreal Engine 4.27

Pull Request Description:

Hello! I really enjoyed using your plugin, and I needed to adjust it to work with an Unreal Engine 4.27 project. This pull request includes modifications to add support for UE4.27.

Summary of Changes
Replaced some UE5-specific modules with equivalent or alternative modules available in UE4.27.
Updated unsupported macros and functions to compatible versions in UE4.27, while keeping the original functionality intact.

Notes
No changes were made to the setup process, so the integration steps remain the same.
All adjustments were made to ensure compatibility without altering the primary logic of the plugin.
Thanks for considering this contribution! I’d be happy to discuss any adjustments or improvements if needed.

2024-11-09 01:51 UTC, ZhengzhongSun commented
Thank you for your love for this project! I'm very sorry for seeing it so late. I'll check it this weekend.

2024-12-30 12:59 UTC, waelarafa commented
Thanks man ^^

2024-12-31 08:07 UTC, ZhengzhongSun requested changes
Please fix about these reviews if you want to contribute to this repo.

2024-12-31 08:07 UTC, ZhengzhongSun commented on README.md
> +- UE 4.27
add UE5 support description to let people know it supports both UE 4.27 and UE 5 now

2024-12-31 08:07 UTC, ZhengzhongSun commented on README.md
> +- [x] Add a diff between branches while using source control E.g. Perforce.
Is this what you want to do? Actually UE5 already have a function to diff with previous commit internally, there is a Diff button in Blueprint. Sometimes both my colleague and I modified the same blueprint, I need to know what my colleague modified before merge it, so I develop this plugin to help me.

2024-12-31 08:07 UTC, ZhengzhongSun commented on Source/BPDiffer/BPDiffer.Build.cs
Actually you don't need to make any modifications to this file in my test.

2024-12-31 08:07 UTC, ZhengzhongSun commented on Source/BPDiffer/Private/BPDifferStyle.cpp
> +
Remove the duplicate empty line.

2025-02-07 14:30 UTC, ZhengzhongSun approved these changes
Use minimal modifications to compatible with UE 4.27

2025-02-07 14:31 UTC, merged